/**********************************************************************************************************************
 * \file CPU_Trap_Recognition.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
/*****************************************************************************/
/* CHANGES                                                                   */
/* ID          dd.mm.yyyy    Name             Description                    */
/* ---         -----------   -----------      ---------------------          */
/* [1]         17.11.2023    Samruddhi Gadave   Added test code for traps    */
/*****************************************************************************/
/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "CPU_Trap_Recognition.h"
#include "Mcal_Compiler.h"
#include "Ifx_reg.h"
#include "mwram_ecc_test.h"


/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/ 
/* Base address of the first MBIST (Memory Built In Self Test) Control Block */
#define IFXMTU_MC_ADDRESS_BASE      (0xF0061000u)
/* Select the DMA module for MBIST */
#define MBIST_REGISTER              IfxMtu_MbistSel_dma


#define TRT_UNALIGNED_ADDRESS           (0xa0000123)
/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
/* Different trap types are supported:
 *  - synchronous or asynchronous
 *  - hardware or software
 * Three different trap type combinations are supported and can be provoked by setting one of each variable to TRUE.
 */
U16 g_provokeSynchronousHardwareTrap = FALSE;
U16 g_provokeAsynchronousHardwareTrap = FALSE;
U16 g_provokeSynchronousSoftwareTrap = FALSE;
U16 g_provokeClass1Trap = FALSE;
U16 g_provokeClass2Trap = FALSE;
U16 g_provokeClass3Trap = FALSE;
U16 g_provokeClass6Trap = FALSE;


/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/* Depending on the values of the g_provokeXYTrap (X = Synchronous / Asynchronous; Y = Hardware / Software) global
 * variables, the following function provokes three different trap types if the AVOID_PROVOCATION is set to FALSE.
 */
void run_trap_provocation(void)
{
    if(g_provokeSynchronousHardwareTrap) /* The following code is based on the example MTU_MBIST_1 */
    {
        /* Get the pointer to Read Data and Bit Flip Register of specific MBIST module */
        Ifx_MTU_MC *mc = (Ifx_MTU_MC *)(IFXMTU_MC_ADDRESS_BASE + 0x100 * MBIST_REGISTER);

        /* Modify the register value. If the above steps are not done, it is causing a Data Access Synchronous Error */
        mc->RDBFL[0].U++;

    }
    else if(g_provokeAsynchronousHardwareTrap) /* The following code is based on the example SMU_IR_Alarm_1 */
    {
        /* Modify the register value. If the above steps are not done, it is causing a Data Access Asynchronous Error*/
        MODULE_SMU.AGC.B.IGCS0 = 1;
    }
    else if(g_provokeSynchronousSoftwareTrap)
    {
        Ifx_CPU_PSW psw;        /* Variable of the type PSW (Program Status Word, General Purpose Register)          */

        /* Get the content of the Program Status Word register with __mfcr instruction (Move From Core Register)     */
        psw.U   = __mfcr(CPU_PSW);
        psw.B.USB = 0x40;       /* Set the overflow bit in the PSV register                                          */

        __mtcr(CPU_PSW, psw.U); /* Write the modified register value with the __mtcr instruction                     */

        /* TRAPV instruction (trap on overflow) call, assembly instruction by using the __asm instruction.
         * If the overflow bit is set, an Arithmetic Overflow Trap will be triggered.
         */
        __asm("trapv");
    }
    else if(g_provokeClass1Trap)
    {
      U32 *Le_ptr = NULL_PTR;
      *Le_ptr = 0x80000000u;
    }
    else if(g_provokeClass2Trap)
    {
        uint32* Local_para = TRT_UNALIGNED_ADDRESS;
    //    *Local_para = 0xA0A0A0A00;
       uint32 Local_para2 = *Local_para;
      __asm__("mov.d %%d2 , %0"::"a"(TRT_UNALIGNED_ADDRESS));
    //    __asm("ld.w   %%d15,[%0]\n\t": :"a"(TRT_UNALIGNED_ADDRESS):"d15");��/*�make�memory�access����*/      

    }
    else if(g_provokeClass3Trap)
    {

       {
    __asm(" mfcr       %%d15, $psw     \n"    /* Backup PSW to d15            */
          " mov        %%d9, %%d15    \n"     /* Copy PSW to d9               */

          " mov        %%d8, 0x80  \n"        /* d8 = 0x00000080              */
          " or         %%d9, %%d9, %%d8 \n"   /* Set CDE = 1;                 */

          " mtcr       $psw, %%d9   \n"       /* Store updated CDE to PSW     */
          " isync                 \n"

          " mov        %%d9, %%d15    \n"     /* Copy PSW to d9               */

          " mov        %%d8, 0x7F  \n"        /* d8 = 0x0000007F              */
          " not        %%d8         \n"       /* d8 = 0xFFFFFF80              */
          " and        %%d9, %%d9, %%d8 \n"   /* Set CDC = 0 (6-bit counter;  */
                                              /* CDC.COUNT = 0)               */
          " mtcr       $psw, %%d9   \n"       /* Store updated CDC to PSW     */
          " isync                 \n"

          " ret                   \n"         /* This instruction will trap   */
                                              /*  because CDC = 0             */

          /* The trap handler will continue execution at the instruction      */
          /* following the one that raised the trap:                          */

          " mtcr    $psw, %%d15     \n"    /* Restore original PSW content    */
          " isync                 \n"
          : : : "d8", "d9", "d15");
        } 
    }
    else if(g_provokeClass6Trap)
    {
         _syscall(1);
    }
    else
    {
        /* Do nothing */
    }
}